@startuml
'https://plantuml.com/class-diagram

Entity Movie
Entity User
Entity Review
Entity WatchList
Entity WatchParty

Movie "1" -- "*" Review : has
Review "1" -- "1" User : written by

User "1" -- "*" WatchList : owns
WatchList "*" -- "*" Movie : contains

User "*" -- "*" WatchParty : participates
WatchParty "*" -- "*" Movie : features

@enduml
